/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_filechooserdialog (void);
GtkWidget* create_fileselection (void);
GtkWidget* create_freqplots_window (void);
GtkWidget* create_rdpattern_window (void);
GtkWidget* create_quit_dialog (void);
GtkWidget* create_error_dialog (void);
GtkWidget* create_animate_dialog (void);
GtkWidget* create_nec2_editor (void);
GtkWidget* create_wire_editor (void);
GtkWidget* create_patch_editor (void);
GtkWidget* create_arc_editor (void);
GtkWidget* create_transform_editor (void);
GtkWidget* create_helix_editor (void);
GtkWidget* create_reflect_editor (void);
GtkWidget* create_scale_editor (void);
GtkWidget* create_cylinder_editor (void);
GtkWidget* create_kernel_command (void);
GtkWidget* create_execute_command (void);
GtkWidget* create_intrange_command (void);
GtkWidget* create_ground_command (void);
GtkWidget* create_nearfield_command (void);
GtkWidget* create_radiation_command (void);
GtkWidget* create_excitation_command (void);
GtkWidget* create_frequency_command (void);
GtkWidget* create_loading_command (void);
GtkWidget* create_network_command (void);
GtkWidget* create_txline_command (void);
GtkWidget* create_ground2_command (void);
GtkWidget* create_gend_editor (void);
GtkWidget* create_aboutdialog (void);
