/*
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 *  The official website and doumentation for xnec2c is available here:
 *    https://www.xnec2c.org/
 */

#include <ctype.h>
#include "interface.h"
#include "shared.h"
#include "callbacks.h"
#include "gdk_scroll.h"
#include "i18n.h"
#include "themes/theme.h"
#include "color/color_palette.h"
#include "cairo/cairo_fit.h"

/*------------------------------------------------------------------*/

/* is_auto_generated_comment()
 *
 * Check if comment line is auto-generated by xnec2c
 */
  static gboolean
is_auto_generated_comment( const char *line )
{
  const char *p;
  char lower[256];
  size_t i, len;

  if( line == NULL )
    return( FALSE );

  len = strlen( line );
  if( len >= sizeof(lower) )
    len = sizeof(lower) - 1;

  for( i = 0; i < len; i++ )
    lower[i] = (char)tolower( (int)line[i] );
  lower[len] = '\0';

  if( strstr(lower, "xnec2c") == NULL )
    return( FALSE );

  p = strstr( lower, "created" );
  if( p == NULL )
    p = strstr( lower, "edited" );

  return( p != NULL );
}

/*------------------------------------------------------------------*/

/* Window_Title_Subject()
 *
 * Fills @buf with the active title subject: the first human-authored CM
 * comment, else the input filename, else the package string, truncated to
 * fit the window-title field.
 */
  void
Window_Title_Subject( char *buf, size_t len )
{
  int fname_idx, i;
  const char *valid_comment;

  valid_comment = NULL;
  if( comments.num > 0 && comments.lines != NULL )
  {
    for( i = 0; i < comments.num; i++ )
    {
      if( comments.lines[i] == NULL || comments.lines[i][0] == '\0' )
        continue;

      if( is_auto_generated_comment(comments.lines[i]) )
        continue;

      valid_comment = comments.lines[i];
      break;
    }
  }

  if( valid_comment != NULL )
  {
    Strlcpy( buf, valid_comment, len );
  }
  else if( strlen(rc_config.input_file) > 0 )
  {
    Get_Dirname( rc_config.input_file, NULL, &fname_idx );
    Strlcpy( buf, &rc_config.input_file[fname_idx], len );
  }
  else
  {
    Strlcpy( buf, PACKAGE_STRING, len );
  }

  if( strlen(buf) > 60 )
  {
    buf[57] = '.';
    buf[58] = '.';
    buf[59] = '.';
    buf[60] = '\0';
  }

} /* Window_Title_Subject() */

/*------------------------------------------------------------------*/

/* Update_Window_Titles()
 *
 * Updates main and editor window titles with CM card or filename
 */
  void
Update_Window_Titles( void )
{
  char title[256];
  char display_text[128];

  if( CHILD )
    return;

  Window_Title_Subject( display_text, sizeof(display_text) );

  if( main_window != NULL )
  {
    snprintf( title, sizeof(title), _("xnec2c Main: %s"), display_text );
    gtk_window_set_title( GTK_WINDOW(main_window), title );
  }

  if( nec2_edit_window != NULL )
  {
    snprintf( title, sizeof(title), _("xnec2c Editor: %s"), display_text );
    gtk_window_set_title( GTK_WINDOW(nec2_edit_window), title );
  }

  if( freqplots_window != NULL )
  {
    snprintf( title, sizeof(title), _("xnec2c Frequency Plots: %s"), display_text );
    gtk_window_set_title( GTK_WINDOW(freqplots_window), title );
  }

  if( rdpattern_window != NULL )
  {
    snprintf( title, sizeof(title), _("xnec2c Radiation Pattern: %s"), display_text );
    gtk_window_set_title( GTK_WINDOW(rdpattern_window), title );
  }

} /* Update_Window_Titles() */

/*------------------------------------------------------------------*/

  GtkWidget *
Builder_Get_Object( GtkBuilder *builder, const gchar *name )
{
  GObject *object = gtk_builder_get_object( builder, name );

  if( object == NULL )
  {
    Stop( ERR_STOP, "Fatal Error: builder could not find object '%s'", name );
    exit(-1);
  }

  return( GTK_WIDGET(object) );
} /* Builder_Get_Object() */

/*------------------------------------------------------------------*/

/* Gtk_Builder()
 *
 * Returns a GtkBuilder with required objects from file
 */
  static void
Gtk_Builder( GtkBuilder **builder, gchar **object_ids )
{
  GError *gerror = NULL;
  int ret = 0;

  /* Create a builder from object ids */
  *builder = gtk_builder_new();
  ret = (int)gtk_builder_add_objects_from_resource(
      *builder, "/xnec2c.glade", object_ids, &gerror );
  if( !ret )
  {
    pr_err("failed to add objects to builder: %s\n", gerror->message);

    pr_err("Listing Object Ids:\n");
    int idx = 0;
    while( object_ids[idx] != NULL )
    {
      pr_err("%s\n", object_ids[idx]);
      idx++;
    }

    exit( -1 );
  }

  /* Connect signals if gmodule is supported */
#if HAVE_G_MODULE_SUPPORTED
  if( !g_module_supported() )
  {
    pr_warn("libgmodule not supported: xnec2c may not function properly on this platform.\n");
  }
#else
    pr_warn("libgmodule not supported: xnec2c may not function properly on this platform.\n");
#endif

  gtk_builder_connect_signals( *builder, NULL );

} /* Gtk_Builder() */

/*------------------------------------------------------------------*/

  GtkWidget *
create_main_window( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { MAIN_WINDOW_IDS };
  Gtk_Builder( builder, object_ids );
  scroll_install_all_spins( *builder );
  color_family_menu_attach( *builder );
  ret = Builder_Get_Object( *builder, "main_window" );
  return( ret );
}

  GtkWidget *
create_filechooserdialog( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { FILECHOOSER_DIALOG_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "filechooserdialog" );
  return( ret );
}

  GtkWidget *
create_freqplots_window( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { FREQPLOTS_WINDOW_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "freqplots_window" );

  /* Per-purpose plot widths load once with the window; the Color Theme
   * submenu is generated from the startup-initialized theme registry. */
  fp_width_init();
  freqplots_theme_menu_build( *builder );

  return( ret );
}

/* Build a detached popup window holding one frequency-plot graph.  Hand-built
 * rather than loaded from glade so it carries only the Cairo drawing area,
 * without the main window's toolbars, menus, or metric entries.  The drawing
 * area binds the freqplots input handlers and stores its view so each handler
 * resolves its target uniformly. */
  GtkWidget *
create_freqplots_popup_window( freqplots_view_t *view, const char *graph_name )
{
  GtkWidget *win, *da;
  char title[256], subject[128];

  win = gtk_window_new( GTK_WINDOW_TOPLEVEL );
  gtk_window_set_default_size( GTK_WINDOW(win), 640, 480 );

  /* Title once at creation: a popup renders one fixed graph type, so the
   * title needs no later refresh. */
  Window_Title_Subject( subject, sizeof(subject) );
  snprintf( title, sizeof(title), _("xnec2c %s: %s"), graph_name, subject );
  gtk_window_set_title( GTK_WINDOW(win), title );

  /* Stack the selected-frequency readout bar above the drawing area so the
   * popup shows its graph's metric values by name. */
  GtkWidget *vbox = gtk_box_new( GTK_ORIENTATION_VERTICAL, 0 );
  gtk_container_add( GTK_CONTAINER(win), vbox );

  /* One top row gives the readout bar the leading width and pins an optional
   * port selector at its minimum width against the right edge, matching the
   * main window; a graph that never follows the port contributes no selector
   * and the readout bar fills the row alone. */
  GtkWidget *topbar = gtk_box_new( GTK_ORIENTATION_HORIZONTAL, 0 );
  gtk_box_pack_start( GTK_BOX(topbar),
      freqplots_readout_bar_new( view ), TRUE, TRUE, 0 );
  GtkWidget *port_combo = freqplots_port_combo_new( view );
  if( port_combo != NULL )
    gtk_box_pack_end( GTK_BOX(topbar), port_combo, FALSE, FALSE, 0 );
  gtk_box_pack_start( GTK_BOX(vbox), topbar, FALSE, FALSE, 0 );

  da = gtk_drawing_area_new();
  gtk_box_pack_start( GTK_BOX(vbox), da, TRUE, TRUE, 0 );
  gtk_widget_add_events( da,
      GDK_BUTTON_PRESS_MASK | GDK_SCROLL_MASK | GDK_SMOOTH_SCROLL_MASK |
      GDK_BUTTON_MOTION_MASK );

  view->window = win;
  g_object_set_data( G_OBJECT(da), "fp_view", view );

  g_signal_connect( da, "draw",
      G_CALLBACK(on_freqplots_drawingarea_draw), NULL );
  g_signal_connect( da, "configure-event",
      G_CALLBACK(on_freqplots_drawingarea_configure_event), NULL );
  g_signal_connect( da, "button-press-event",
      G_CALLBACK(on_freqplots_drawingarea_button_press_event), NULL );
  g_signal_connect( da, "scroll-event",
      G_CALLBACK(on_freqplots_drawingarea_scroll_event), NULL );
  g_signal_connect( da, "motion-notify-event",
      G_CALLBACK(on_freqplots_drawingarea_motion_notify_event), NULL );
  g_signal_connect( win, "destroy",
      G_CALLBACK(on_freqplots_popup_destroy), view );
  g_signal_connect( win, "key-press-event",
      G_CALLBACK(on_freqplots_popup_key_press_event), NULL );

  /* Present the surface once its handlers are attached, so the show and
   * resize this triggers reach the draw and configure callbacks. */
  view->canvas = canvas_create( da, &cairo_engine );

  return( win );
}

  GtkWidget *
create_rdpattern_window( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { RDPATTERN_WINDOW_IDS };
  Gtk_Builder( builder, object_ids );
  scroll_install_all_spins( *builder );
  ret = Builder_Get_Object( *builder, "rdpattern_window" );
  return( ret );
}

  GtkWidget *
create_quit_dialog( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { QUIT_DIALOG_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "quit_dialog" );
  return( ret );
}

  GtkWidget *
create_error_dialog( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { ERROR_DIALOG_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "error_dialog" );
  return( ret );
}

  GtkWidget *
create_animate_dialog( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  GError *gerror = NULL;

  /* Load the standalone animate dialog whole through its own builder,
   * mirroring sy_overrides_init rather than filtering ids from xnec2c.glade. */
  *builder = gtk_builder_new();
  if( !gtk_builder_add_from_resource( *builder, "/animate.glade", &gerror ) )
  {
    pr_err("create_animate_dialog: failed to load animate.glade: %s\n", gerror->message);
    exit( -1 );
  }
  gtk_builder_connect_signals( *builder, NULL );
  ret = Builder_Get_Object( *builder, "animate_dialog" );
  return( ret );
}

  GtkWidget *
create_nec2_editor( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { NEC2_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "nec2_editor" );
  return( ret );
}

  GtkWidget *
create_wire_editor( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { WIRE_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "wire_editor" );
  return( ret );
}

  GtkWidget *
create_patch_editor( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { PATCH_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "patch_editor" );
  return( ret );
}

  GtkWidget *
create_arc_editor( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { ARC_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "arc_editor" );
  return( ret );
}

  GtkWidget *
create_transform_editor( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { TRANSFORM_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "transform_editor" );
  return( ret );
}

  GtkWidget *
create_helix_editor( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { HELIX_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "helix_editor" );
  return( ret );
}

  GtkWidget *
create_reflect_editor( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { REFLECT_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "reflect_editor" );
  return( ret );
}

  GtkWidget *
create_scale_editor( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { SCALE_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "scale_editor" );
  return( ret );
}

  GtkWidget *
create_cylinder_editor( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { CYLINDER_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "cylinder_editor" );
  return( ret );
}

  GtkWidget *
create_kernel_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { KERNEL_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "kernel_command" );
  return( ret );
}

  GtkWidget *
create_execute_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { EXECUTE_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "execute_command" );
  return( ret );
}

  GtkWidget *
create_intrange_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { INTRANGE_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "intrange_command" );
  return( ret );
}

  GtkWidget *
create_zo_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { ZO_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "zo_command" );
  return( ret );
}

  GtkWidget *
create_ground_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { GROUND_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "ground_command" );
  return( ret );
}

  GtkWidget *
create_nearfield_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { NEARFIELD_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "nearfield_command" );
  return( ret );
}

  GtkWidget *
create_radiation_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { RADIATION_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "radiation_command" );
  return( ret );
}

  GtkWidget *
create_excitation_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { EXCITATION_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "excitation_command" );
  return( ret );
}

  GtkWidget *
create_frequency_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { FREQUENCY_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "frequency_command" );
  return( ret );
}

  GtkWidget *
create_loading_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { LOADING_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "loading_command" );
  return( ret );
}

  GtkWidget *
create_network_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { NETWORK_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "network_command" );
  return( ret );
}

  GtkWidget *
create_txline_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { TXLINE_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "txline_command" );
  return( ret );
}

  GtkWidget *
create_ground2_command( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { GROUND2_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "ground2_command" );
  return( ret );
}

  GtkWidget *
create_gend_editor( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { GEND_EDITOR_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "gend_editor" );
  return( ret );
}

  GtkWidget *
create_aboutdialog( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { ABOUT_DIALOG_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "aboutdialog" );
  return( ret );
}

  GtkWidget *
create_nec2_save_dialog( GtkBuilder **builder )
{
  GtkWidget *ret = NULL;
  gchar *object_ids[] = { SAVE_DIALOG_IDS };
  Gtk_Builder( builder, object_ids );
  ret = Builder_Get_Object( *builder, "nec2_save_dialog" );
  return( ret );
}

