name: Build DEB Packages

on:
  push:
    branches:
      - wf-test
  pull_request:
    branches:
      - wf-test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: 
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
          - debian-11
          - debian-10
          - debian-9
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up the build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            libgtk-3-dev \
            libglib2.0-dev \
            gettext \
            desktop-file-utils \
            devscripts \
            fakeroot \
            lintian \
            autopoint \
            dh-make \
            dh-autoreconf

      - name: Determine version and dist
        id: version
        shell: bash
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          TAGGED_COMMIT=$(git describe --tags --exact-match 2>/dev/null || echo "notag")
          
          if [ "$TAGGED_COMMIT" = "notag" ]; then
            VERSION="${LATEST_TAG}+"
            DIST="-git"
          else
            VERSION=$LATEST_TAG
            DIST=""
          fi

          # Clean version string
          VERSION=$(echo $VERSION | sed -e 's/^v//' -e 's/[+]//g')

          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "DIST=${DIST}" >> $GITHUB_ENV

      - name: Generate Debian Packaging Files
        run: |
          rm -rf ./debian
          dh_make --createorig -y --single --native --packagename xnec2c_${VERSION}
          
          cat > debian/rules << 'EOF'
          #!/usr/bin/make -f
          %:
          	dh $@
          EOF
          chmod +x debian/rules
          
          cat > debian/control << EOF
          Source: xnec2c
          Section: utils
          Priority: optional
          Maintainer: Your Name <you@example.com>
          Build-Depends: debhelper (>= 9), 
            autotools-dev,
            automake,
            autoconf,
            libtool,
            libgtk-3-dev,
            libglib2.0-dev,
            gettext,
            desktop-file-utils
          Standards-Version: 3.9.6
          Homepage: https://www.example.com

          Package: xnec2c
          Architecture: any
          Depends: \${shlibs:Depends}, \${misc:Depends}
          Description: EM tool for antenna radiation pattern modeling
           Xnec2c is a high-performance multi-threaded electromagnetic simulation
           package to model antenna near- and far-field radiation patterns for
           Linux and UNIX operating systems.
          EOF
          
          echo "9" > debian/compat

      - name: Generate Debian Changelog
        run: |
          {
            echo "xnec2c (${VERSION}${DIST}) unstable; urgency=low"
            echo ""
            git log --pretty=format:"  * %s"
            echo ""
            echo " -- Your Name <you@example.com>  $(date -R)"
          } > debian/changelog

      - name: Build DEB package
        run: |
          ./autogen.sh
          ./configure
          make -j$(nproc)
          debuild -us -uc -b

      - name: Test DEB package
        run: |
          sudo dpkg -i ../xnec2c_*.deb || sudo apt-get -f install -y
          xnec2c -h

      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: xnec2c-${{ matrix.os }}.deb
          path: ../xnec2c_*.deb
          retention-days: 7
